from __future__ import annotations

from typing import Protocol

from multi_iterm2_manager.models import CreateTerminalParams, TerminalFrame, TerminalHandle, TerminalRuntimeInfo


class TerminalBackend(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def cleanup_managed_terminals(self) -> int: ...

    async def create_terminal(self, params: CreateTerminalParams) -> TerminalHandle: ...

    async def get_screen_render(self, handle: TerminalHandle) -> tuple[str, str]: ...

    async def get_screen_text(self, handle: TerminalHandle) -> str: ...

    async def stream_screen(self, handle: TerminalHandle): ...

    async def send_text(self, handle: TerminalHandle, text: str) -> None: ...

    async def focus(self, handle: TerminalHandle) -> None: ...

    def is_session_focused(self, session_id: str) -> bool: ...

    async def start_focus_monitor(self) -> None: ...

    async def stop_focus_monitor(self) -> None: ...

    async def rename(self, handle: TerminalHandle, name: str) -> None: ...

    async def hide_app(self) -> None: ...

    async def maybe_quit_app(self) -> None: ...

    async def close(self, handle: TerminalHandle) -> None: ...

    async def set_frame(self, handle: TerminalHandle, frame: TerminalFrame) -> None: ...

    async def get_frame(self, handle: TerminalHandle) -> TerminalFrame | None: ...

    async def get_cwd(self, handle: TerminalHandle) -> str | None: ...

    async def get_runtime_info(self, handle: TerminalHandle) -> TerminalRuntimeInfo: ...
