from __future__ import annotations

from typing import Protocol

from multi_iterm2_manager.models import CreateTerminalParams, TerminalFrame, TerminalHandle


class TerminalBackend(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def cleanup_managed_terminals(self) -> int: ...

    async def ensure_anchor_terminal(self) -> None: ...

    async def create_terminal(self, params: CreateTerminalParams) -> TerminalHandle: ...

    async def get_screen_text(self, handle: TerminalHandle) -> str: ...

    async def stream_screen(self, handle: TerminalHandle): ...

    async def send_text(self, handle: TerminalHandle, text: str) -> None: ...

    async def focus(self, handle: TerminalHandle) -> None: ...

    async def rename(self, handle: TerminalHandle, name: str) -> None: ...

    async def hide_app(self) -> None: ...

    async def maybe_quit_app(self) -> None: ...

    async def close(self, handle: TerminalHandle) -> None: ...

    async def set_frame(self, handle: TerminalHandle, frame: TerminalFrame) -> None: ...

    async def get_frame(self, handle: TerminalHandle) -> TerminalFrame | None: ...
